name: check_cran
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check for CRAN
      env:
        RHUB_EMAIL: nhlapi@jozef.io
      run: sh ci/docker_stage.sh ci/check_rhub.R "cran"
