name: test_coverage
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Covr test_coverage
      env:
        NHLAPI_REMOTE_TESTS: true
        NHLAPI_TOKEN_CODECOV: ${{ secrets.NHLAPI_TOKEN_CODECOV }}
      run: sh ci/docker_stage.sh ci/test_coverage.R
