name: test_remote_api
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: All remote tests
      env:
        NHLAPI_REMOTE_TESTS: true
      run: sh ci/docker_stage.sh ci/test_all.R
